name: minecart-routing
version: '1.0-SNAPSHOT'
main: ec.brooke.minecartrouting.MinecartRouting
api-version: '1.21'
authors: [ brooke.ec ]
description: Reuse oxidized copper golems for computational tasks
